version: '3.3'
services:
  banco:
    build: .
    network_mode: bridge
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8080:8080'
    links:
      - 'db:database'
    expose:
      # Opens port 3306 on the container
      - '8080'
    volumes:
      - ./componentes/lanzador/application.properties:/aplicacion/application.properties
  db:
    image: mysql:5.7.39
    restart: always
    network_mode: bridge
    environment:
      MYSQL_DATABASE: 'banco'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'u_banco'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pw_banco'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    #volumes:
      #- my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
