-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: curso04-ejerc013/changelog-2.0.0.xml
-- Ran at: 8/11/22, 9:44 AM
-- Against: null@offline:h2
-- Liquibase version: 4.15.0
-- *********************************************************************

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-1::curso04 (generated)
CREATE TABLE PUBLIC.apunte (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, externa BOOLEAN NOT NULL, importe FLOAT(12) NOT NULL, cuenta_id BIGINT, CONSTRAINT PK_APUNTE PRIMARY KEY (id));

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-2::curso04 (generated)
CREATE TABLE PUBLIC.cuenta (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, activa BOOLEAN NOT NULL, iban VARCHAR(255) NOT NULL, saldo DOUBLE NOT NULL, CONSTRAINT PK_CUENTA PRIMARY KEY (id), UNIQUE (iban));

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-3::curso04 (generated)
CREATE TABLE PUBLIC.ingreso (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, apunte_id BIGINT, CONSTRAINT PK_INGRESO PRIMARY KEY (id));

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-4::curso04 (generated)
CREATE TABLE PUBLIC.retiro (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, apunte_id BIGINT, CONSTRAINT PK_RETIRO PRIMARY KEY (id));

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-5::curso04 (generated)
CREATE TABLE PUBLIC.transferencia (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingreso_id BIGINT, retiro_id BIGINT, CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (id));

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-6::curso04 (generated)
CREATE INDEX PUBLIC.FK6ve9k0ej3ght64fj4kar62h8h ON PUBLIC.ingreso(apunte_id);

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-7::curso04 (generated)
CREATE INDEX PUBLIC.FK707y0ebiwruxr5ofedks42aox ON PUBLIC.retiro(apunte_id);

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-8::curso04 (generated)
CREATE INDEX PUBLIC.FKa728wcqgd0y1si6d84u0hmln9 ON PUBLIC.transferencia(ingreso_id);

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-9::curso04 (generated)
CREATE INDEX PUBLIC.FKbwkn4y5wfdiqgymq0yjdv0w9c ON PUBLIC.transferencia(retiro_id);

-- Changeset curso04-ejerc013/changelog-2.0.0.xml::1660203864273-10::curso04 (generated)
CREATE INDEX PUBLIC.FKrs5hx0yw2tc6awund154m5xic ON PUBLIC.apunte(cuenta_id);

